spring:
  profiles:
    active:
    - dev
   
---
# 开发环境
spring:
  profiles: dev
  application:
    name: abcmsc-config-dev
    
# 测试环境
---
spring:
  profiles: test
  application:
    name: abcmsc-config-test
